41 handle error in controller
GSG-G13/code-academy-api pull request #42
Opened 2023-06-12 13:17 UTC by KhaledAref13

2023-06-12 20:17 UTC, Nour-Agha99 approved these changes

2023-06-12 20:30 UTC, Shatha-Amin approved these changes

2023-06-12 20:48 UTC, karamzomlot requested changes

2023-06-12 20:48 UTC, karamzomlot commented on src/controllers/errors/clientError.ts
> +      message: 'Bad Request',
The message should be `404 Error` not `Bad Request`

2023-06-12 20:48 UTC, karamzomlot commented on src/database/config/fakeData.sql
> +  ('Admin', 'admin', 'codeacademy.gsg@gmail.com', '$2b$10$EXkKb.e1TQrSJkoGnbQ2nO5.V2uWuIOeLqwICylJEj5cG1BTXblBa', 'avatar2.jpg', true, 2);
As Nour said the admin user inserted in build file. There is no need to add it here

2023-06-12 22:12 UTC, karamzomlot requested changes

2023-06-12 22:12 UTC, karamzomlot commented on src/database/config/fakeData.sql
Should end the query with semicolon not coma.

2023-06-13 08:12 UTC, Batrawi approved these changes

2023-06-13 08:27 UTC, karamzomlot approved these changes

2023-06-13 08:27 UTC, merged