50 create edit post controller
GSG-G13/code-academy-api pull request #55
Opened 2023-06-14 17:44 UTC by KhaledAref13

2023-06-15 15:43 UTC, karamzomlot requested changes

2023-06-15 15:43 UTC, karamzomlot commented on src/routes/posts/index.ts
> +postsRouter.put('/:postId', editPostController);
@KhaledAref13
I'd prefer to rename the parameter to `id` instead of `postId` like what Shatha did in the delete post route

2023-06-15 15:43 UTC, karamzomlot commented on src/utils/types/helpers/posts/EditPost.ts
> +interface EditPost {
Rename interface to `EditPostQuery` and rename `postId` to `id`

2023-06-15 15:43 UTC, karamzomlot commented on src/utils/validation/posts/editPostSchema.ts
> +  postId: Joi.number().required().messages({
The same here rename `postId` to `id`

2023-06-16 02:33 UTC, Nour-Agha99 approved these changes

2023-06-17 12:03 UTC, Shatha-Amin approved these changes

2023-06-17 18:31 UTC, karamzomlot approved these changes

2023-06-17 18:50 UTC, Batrawi approved these changes

2023-06-17 18:50 UTC, merged