75 get members
GSG-G13/code-academy-api pull request #76
Opened 2023-06-23 22:46 UTC by Nour-Agha99

2023-06-24 05:31 UTC, karamzomlot requested changes

2023-06-24 05:31 UTC, karamzomlot commented on src/controllers/users/getMembersController.ts
> +    const offset = (Number(page || 1) - 1) * 10;
I think you should multiply the number of pages by 12 not 10 Coz the number of items per page is 12

2023-06-24 05:31 UTC, karamzomlot commented on src/controllers/users/getMembersController.ts
> +    const countOfMembers = members.length;
Try to add 20 users ang get all of them by this controller and let me know about the countOfMembers will return in response

2023-06-24 09:49 UTC, Shatha-Amin approved these changes

2023-06-24 15:02 UTC, KhaledAref13 approved these changes

2023-06-25 06:33 UTC, Batrawi approved these changes

2023-06-25 08:18 UTC, karamzomlot approved these changes

2023-06-25 08:18 UTC, merged