82 edit all cohorts query
GSG-G13/code-academy-api pull request #83
Opened 2023-07-02 14:58 UTC by Shatha-Amin

2023-07-02 17:42 UTC, Batrawi approved these changes

2023-07-02 19:16 UTC, Nour-Agha99 approved these changes

2023-07-04 08:53 UTC, karamzomlot commented on src/utils/types/helpers/AllCohortsQueryArgs.ts
> +  limit?: number;
No limit!!

2023-07-04 08:56 UTC, karamzomlot requested changes

2023-07-04 08:56 UTC, karamzomlot commented on package.json
> +    "react-query": "^3.39.3",
react-query !!!

2023-07-04 09:07 UTC, KhaledAref13 approved these changes

2023-07-04 09:08 UTC, karamzomlot approved these changes

2023-07-04 09:09 UTC, merged