81 get single member page with all information user profile
GSG-G13/code-academy-api pull request #84
Opened 2023-07-02 17:39 UTC by Batrawi

2023-07-02 17:42 UTC, Shatha-Amin approved these changes

2023-07-02 22:07 UTC, Nour-Agha99 requested changes

2023-07-02 22:07 UTC, Nour-Agha99 commented on src/controllers/users/getSingleMemberController.ts
> +    await validateGetSingleMember.validateAsync({ id });
req.params always became string 
so make id number before to validate

2023-07-02 22:07 UTC, Nour-Agha99 commented on src/controllers/users/getSingleMemberController.ts
> +        message: 'Member returned successfully',
add error state in the response

2023-07-02 22:07 UTC, Nour-Agha99 commented on src/controllers/users/getSingleMemberController.ts
> +    const { rows, rowCount } = await getSingleMemberQuery({ memberId: +id });
make label to rows to be more readable

2023-07-03 08:22 UTC, Batrawi commented on src/controllers/users/getSingleMemberController.ts
> +    const { rows, rowCount } = await getSingleMemberQuery({ memberId: +id });
make it clear

2023-07-04 09:43 UTC, KhaledAref13 approved these changes

2023-07-04 09:57 UTC, karamzomlot requested changes

2023-07-04 09:57 UTC, karamzomlot commented on src/database/query/users/getSingleMemberQuery.ts
> +        career_status.name AS career_status,
No need to add `As career_status`. Just add it if you want to edit the column name when returning the data

2023-07-04 11:27 UTC, karamzomlot approved these changes

2023-07-04 11:29 UTC, Nour-Agha99 approved these changes

2023-07-04 11:30 UTC, merged