87 add a comments
GSG-G13/code-academy-api pull request #88
Opened 2023-07-03 10:09 UTC by Nour-Agha99

2023-07-03 10:15 UTC, Shatha-Amin approved these changes

2023-07-04 08:14 UTC, Batrawi approved these changes

2023-07-04 09:42 UTC, KhaledAref13 approved these changes

2023-07-04 10:16 UTC, karamzomlot requested changes

2023-07-04 10:16 UTC, karamzomlot commented on src/controllers/comments/addCommentController.ts
> +    const userId = req.user?.id;
Use destructuring

2023-07-04 10:16 UTC, karamzomlot commented on src/controllers/comments/addCommentController.ts
> +    if (!posts.length) throw new CustomError('NOT FOUND', 404);
Be more descriptive (Post Not Found)

2023-07-04 10:16 UTC, karamzomlot commented on src/controllers/comments/addCommentController.ts
> +      throw new CustomError('NOT FOUND', 404);
Unauthorized error!!

2023-07-04 12:07 UTC, karamzomlot approved these changes

2023-07-04 12:07 UTC, merged